name: deploy-public

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Public Release
        run: |
          composer install --no-dev
          npm install
          npm run production
      - uses: docker://sitepilot/wp-ftp-deploy:latest
        env:
          SP_UPDATE_VER: public-v1
          SP_FTP_PASSWORD: ${{ secrets.SP_FTP_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.SP_GITHUB_TOKEN }}
